# Generated by Django 5.0.4 on 2024-05-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_rename_vuelos_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='codigo_vuelo',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
