# Generated by Django 5.0.4 on 2024-05-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_clientes_codigo_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codigo_vuelo',
            field=models.IntegerField(null=True),
        ),
    ]
