# Generated by Django 5.0.4 on 2024-05-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_clientes_codigo_vuelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='codigo_vuelo',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='mail',
        ),
    ]
