# Generated by Django 5.0.4 on 2024-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=100, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
    ]
